service: serverless-backend
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  memorySize: 512
  timeout: 10
  # environment:
    # database: ${env:database,"fallback"}


functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: "*"
          # path: '/{default*}'
          # method: any
          # cors:
          #   allowedOrigins: ${env:CORS_ORIGIN,"*"}
          #   allowedHeaders:
          #     - Content-Type
          #     - Authorization
          #   allowCredentials: true
      

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
